name: Update npm package

on:
    release:
        types: [published]
    push:
        branches:
            - main

jobs:
    releaser:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - uses: mmarchini-oss/npm-otp-publish@v0
          with:
            npm_token: ${{ secrets.NPM_TOKEN }}
            github_token: ${{ secrets.GH_ACCOUNT_TOKEN }}
            github_actor: ${{ github.actor }}
